// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// my_setdiff1
arma::uvec my_setdiff1(arma::uvec& x, const arma::uvec& y);
RcppExport SEXP _BatchReMeasure_my_setdiff1(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(my_setdiff1(x, y));
    return rcpp_result_gen;
END_RCPP
}
// Update_rho_S1
double Update_rho_S1(arma::mat Zc1, arma::mat Zc2, arma::vec Yc1, arma::vec Yc2, double a0H, double a1H, arma::vec betaH, double sigma1H, double sigma2H, arma::uvec Index);
RcppExport SEXP _BatchReMeasure_Update_rho_S1(SEXP Zc1SEXP, SEXP Zc2SEXP, SEXP Yc1SEXP, SEXP Yc2SEXP, SEXP a0HSEXP, SEXP a1HSEXP, SEXP betaHSEXP, SEXP sigma1HSEXP, SEXP sigma2HSEXP, SEXP IndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Zc1(Zc1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc2(Zc2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc1(Yc1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc2(Yc2SEXP);
    Rcpp::traits::input_parameter< double >::type a0H(a0HSEXP);
    Rcpp::traits::input_parameter< double >::type a1H(a1HSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1H(sigma1HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2H(sigma2HSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index(IndexSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_rho_S1(Zc1, Zc2, Yc1, Yc2, a0H, a1H, betaH, sigma1H, sigma2H, Index));
    return rcpp_result_gen;
END_RCPP
}
// Update_sigma1_S1
double Update_sigma1_S1(arma::mat Zc1, arma::mat Zc2, arma::vec Yc1, arma::vec Yc2, double a0H, double a1H, arma::vec betaH, double rhoH, double sigma2H, arma::uvec Index);
RcppExport SEXP _BatchReMeasure_Update_sigma1_S1(SEXP Zc1SEXP, SEXP Zc2SEXP, SEXP Yc1SEXP, SEXP Yc2SEXP, SEXP a0HSEXP, SEXP a1HSEXP, SEXP betaHSEXP, SEXP rhoHSEXP, SEXP sigma2HSEXP, SEXP IndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Zc1(Zc1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc2(Zc2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc1(Yc1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc2(Yc2SEXP);
    Rcpp::traits::input_parameter< double >::type a0H(a0HSEXP);
    Rcpp::traits::input_parameter< double >::type a1H(a1HSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< double >::type rhoH(rhoHSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2H(sigma2HSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index(IndexSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_sigma1_S1(Zc1, Zc2, Yc1, Yc2, a0H, a1H, betaH, rhoH, sigma2H, Index));
    return rcpp_result_gen;
END_RCPP
}
// Update_sigma2_S1
double Update_sigma2_S1(arma::mat Zc1, arma::mat Zt2, arma::mat Zc2, arma::vec Yc1, arma::vec Yt2, arma::vec Yc2, double a0H, double a1H, arma::vec betaH, double rhoH, double sigma1H, arma::uvec Index);
RcppExport SEXP _BatchReMeasure_Update_sigma2_S1(SEXP Zc1SEXP, SEXP Zt2SEXP, SEXP Zc2SEXP, SEXP Yc1SEXP, SEXP Yt2SEXP, SEXP Yc2SEXP, SEXP a0HSEXP, SEXP a1HSEXP, SEXP betaHSEXP, SEXP rhoHSEXP, SEXP sigma1HSEXP, SEXP IndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Zc1(Zc1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zt2(Zt2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc2(Zc2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc1(Yc1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt2(Yt2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc2(Yc2SEXP);
    Rcpp::traits::input_parameter< double >::type a0H(a0HSEXP);
    Rcpp::traits::input_parameter< double >::type a1H(a1HSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< double >::type rhoH(rhoHSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1H(sigma1HSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index(IndexSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_sigma2_S1(Zc1, Zt2, Zc2, Yc1, Yt2, Yc2, a0H, a1H, betaH, rhoH, sigma1H, Index));
    return rcpp_result_gen;
END_RCPP
}
// Update_beta_S1
arma::vec Update_beta_S1(arma::mat Zc1, arma::mat Zt2, arma::mat Zc2, arma::vec Yc1, arma::vec Yt2, arma::vec Yc2, double a0H, double a1H, double rhoH, double sigma1H, double sigma2H, arma::uvec Index);
RcppExport SEXP _BatchReMeasure_Update_beta_S1(SEXP Zc1SEXP, SEXP Zt2SEXP, SEXP Zc2SEXP, SEXP Yc1SEXP, SEXP Yt2SEXP, SEXP Yc2SEXP, SEXP a0HSEXP, SEXP a1HSEXP, SEXP rhoHSEXP, SEXP sigma1HSEXP, SEXP sigma2HSEXP, SEXP IndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Zc1(Zc1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zt2(Zt2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc2(Zc2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc1(Yc1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt2(Yt2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc2(Yc2SEXP);
    Rcpp::traits::input_parameter< double >::type a0H(a0HSEXP);
    Rcpp::traits::input_parameter< double >::type a1H(a1HSEXP);
    Rcpp::traits::input_parameter< double >::type rhoH(rhoHSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1H(sigma1HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2H(sigma2HSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index(IndexSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_beta_S1(Zc1, Zt2, Zc2, Yc1, Yt2, Yc2, a0H, a1H, rhoH, sigma1H, sigma2H, Index));
    return rcpp_result_gen;
END_RCPP
}
// Update_a_S1
arma::vec Update_a_S1(arma::mat Zc1, arma::mat Zt2, arma::mat Zc2, arma::vec Yc1, arma::vec Yt2, arma::vec Yc2, double a0H, double a1H, arma::vec betaH, double rhoH, double sigma1H, double sigma2H, arma::uvec Index);
RcppExport SEXP _BatchReMeasure_Update_a_S1(SEXP Zc1SEXP, SEXP Zt2SEXP, SEXP Zc2SEXP, SEXP Yc1SEXP, SEXP Yt2SEXP, SEXP Yc2SEXP, SEXP a0HSEXP, SEXP a1HSEXP, SEXP betaHSEXP, SEXP rhoHSEXP, SEXP sigma1HSEXP, SEXP sigma2HSEXP, SEXP IndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Zc1(Zc1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zt2(Zt2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc2(Zc2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc1(Yc1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt2(Yt2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc2(Yc2SEXP);
    Rcpp::traits::input_parameter< double >::type a0H(a0HSEXP);
    Rcpp::traits::input_parameter< double >::type a1H(a1HSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< double >::type rhoH(rhoHSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1H(sigma1HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2H(sigma2HSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index(IndexSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_a_S1(Zc1, Zt2, Zc2, Yc1, Yt2, Yc2, a0H, a1H, betaH, rhoH, sigma1H, sigma2H, Index));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_Objective_S1
double Rcpp_Objective_S1(arma::mat Zc1, arma::mat Zt2, arma::mat Zc2, arma::vec Yc1, arma::vec Yt2, arma::vec Yc2, double a0H, double a1H, arma::vec betaH, double rhoH, double sigma1H, double sigma2H, arma::uvec Index);
RcppExport SEXP _BatchReMeasure_Rcpp_Objective_S1(SEXP Zc1SEXP, SEXP Zt2SEXP, SEXP Zc2SEXP, SEXP Yc1SEXP, SEXP Yt2SEXP, SEXP Yc2SEXP, SEXP a0HSEXP, SEXP a1HSEXP, SEXP betaHSEXP, SEXP rhoHSEXP, SEXP sigma1HSEXP, SEXP sigma2HSEXP, SEXP IndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Zc1(Zc1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zt2(Zt2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc2(Zc2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc1(Yc1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt2(Yt2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc2(Yc2SEXP);
    Rcpp::traits::input_parameter< double >::type a0H(a0HSEXP);
    Rcpp::traits::input_parameter< double >::type a1H(a1HSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< double >::type rhoH(rhoHSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1H(sigma1HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2H(sigma2HSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index(IndexSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_Objective_S1(Zc1, Zt2, Zc2, Yc1, Yt2, Yc2, a0H, a1H, betaH, rhoH, sigma1H, sigma2H, Index));
    return rcpp_result_gen;
END_RCPP
}
// my_setdiff2
arma::uvec my_setdiff2(arma::uvec& x, const arma::uvec& y);
RcppExport SEXP _BatchReMeasure_my_setdiff2(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(my_setdiff2(x, y));
    return rcpp_result_gen;
END_RCPP
}
// Update_rho1_S2
double Update_rho1_S2(arma::mat Zc1, arma::mat Zc3, arma::vec Yc1, arma::vec Yc3, double a3H, arma::vec betaH, double sigma1H, double sigma3H, arma::uvec Index_C);
RcppExport SEXP _BatchReMeasure_Update_rho1_S2(SEXP Zc1SEXP, SEXP Zc3SEXP, SEXP Yc1SEXP, SEXP Yc3SEXP, SEXP a3HSEXP, SEXP betaHSEXP, SEXP sigma1HSEXP, SEXP sigma3HSEXP, SEXP Index_CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Zc1(Zc1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc3(Zc3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc1(Yc1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc3(Yc3SEXP);
    Rcpp::traits::input_parameter< double >::type a3H(a3HSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1H(sigma1HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma3H(sigma3HSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index_C(Index_CSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_rho1_S2(Zc1, Zc3, Yc1, Yc3, a3H, betaH, sigma1H, sigma3H, Index_C));
    return rcpp_result_gen;
END_RCPP
}
// Update_rho2_S2
double Update_rho2_S2(arma::mat Zt2, arma::mat Zt3, arma::vec Yt2, arma::vec Yt3, double a0H, double a1H, double a3H, arma::vec betaH, double sigma2H, double sigma3H, arma::uvec Index_T);
RcppExport SEXP _BatchReMeasure_Update_rho2_S2(SEXP Zt2SEXP, SEXP Zt3SEXP, SEXP Yt2SEXP, SEXP Yt3SEXP, SEXP a0HSEXP, SEXP a1HSEXP, SEXP a3HSEXP, SEXP betaHSEXP, SEXP sigma2HSEXP, SEXP sigma3HSEXP, SEXP Index_TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Zt2(Zt2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zt3(Zt3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt2(Yt2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt3(Yt3SEXP);
    Rcpp::traits::input_parameter< double >::type a0H(a0HSEXP);
    Rcpp::traits::input_parameter< double >::type a1H(a1HSEXP);
    Rcpp::traits::input_parameter< double >::type a3H(a3HSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2H(sigma2HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma3H(sigma3HSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index_T(Index_TSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_rho2_S2(Zt2, Zt3, Yt2, Yt3, a0H, a1H, a3H, betaH, sigma2H, sigma3H, Index_T));
    return rcpp_result_gen;
END_RCPP
}
// Update_sigma1_S2
double Update_sigma1_S2(arma::mat Zc1, arma::mat Zc3, arma::vec Yc1, arma::vec Yc3, double a3H, arma::vec betaH, double rho1H, double sigma3H, arma::uvec Index_C);
RcppExport SEXP _BatchReMeasure_Update_sigma1_S2(SEXP Zc1SEXP, SEXP Zc3SEXP, SEXP Yc1SEXP, SEXP Yc3SEXP, SEXP a3HSEXP, SEXP betaHSEXP, SEXP rho1HSEXP, SEXP sigma3HSEXP, SEXP Index_CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Zc1(Zc1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc3(Zc3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc1(Yc1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc3(Yc3SEXP);
    Rcpp::traits::input_parameter< double >::type a3H(a3HSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< double >::type rho1H(rho1HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma3H(sigma3HSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index_C(Index_CSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_sigma1_S2(Zc1, Zc3, Yc1, Yc3, a3H, betaH, rho1H, sigma3H, Index_C));
    return rcpp_result_gen;
END_RCPP
}
// Update_sigma2_S2
double Update_sigma2_S2(arma::mat Zt2, arma::mat Zt3, arma::vec Yt2, arma::vec Yt3, double a0H, double a1H, double a3H, arma::vec betaH, double rho2H, double sigma3H, arma::uvec Index_T);
RcppExport SEXP _BatchReMeasure_Update_sigma2_S2(SEXP Zt2SEXP, SEXP Zt3SEXP, SEXP Yt2SEXP, SEXP Yt3SEXP, SEXP a0HSEXP, SEXP a1HSEXP, SEXP a3HSEXP, SEXP betaHSEXP, SEXP rho2HSEXP, SEXP sigma3HSEXP, SEXP Index_TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Zt2(Zt2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zt3(Zt3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt2(Yt2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt3(Yt3SEXP);
    Rcpp::traits::input_parameter< double >::type a0H(a0HSEXP);
    Rcpp::traits::input_parameter< double >::type a1H(a1HSEXP);
    Rcpp::traits::input_parameter< double >::type a3H(a3HSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< double >::type rho2H(rho2HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma3H(sigma3HSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index_T(Index_TSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_sigma2_S2(Zt2, Zt3, Yt2, Yt3, a0H, a1H, a3H, betaH, rho2H, sigma3H, Index_T));
    return rcpp_result_gen;
END_RCPP
}
// Update_sigma3_S2
double Update_sigma3_S2(arma::mat Zc1, arma::mat Zt2, arma::mat Zc3, arma::mat Zt3, arma::vec Yc1, arma::vec Yt2, arma::vec Yc3, arma::vec Yt3, double a0H, double a1H, double a3H, arma::vec betaH, double rho1H, double rho2H, double sigma1H, double sigma2H, arma::uvec Index_C, arma::uvec Index_T);
RcppExport SEXP _BatchReMeasure_Update_sigma3_S2(SEXP Zc1SEXP, SEXP Zt2SEXP, SEXP Zc3SEXP, SEXP Zt3SEXP, SEXP Yc1SEXP, SEXP Yt2SEXP, SEXP Yc3SEXP, SEXP Yt3SEXP, SEXP a0HSEXP, SEXP a1HSEXP, SEXP a3HSEXP, SEXP betaHSEXP, SEXP rho1HSEXP, SEXP rho2HSEXP, SEXP sigma1HSEXP, SEXP sigma2HSEXP, SEXP Index_CSEXP, SEXP Index_TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Zc1(Zc1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zt2(Zt2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc3(Zc3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zt3(Zt3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc1(Yc1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt2(Yt2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc3(Yc3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt3(Yt3SEXP);
    Rcpp::traits::input_parameter< double >::type a0H(a0HSEXP);
    Rcpp::traits::input_parameter< double >::type a1H(a1HSEXP);
    Rcpp::traits::input_parameter< double >::type a3H(a3HSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< double >::type rho1H(rho1HSEXP);
    Rcpp::traits::input_parameter< double >::type rho2H(rho2HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1H(sigma1HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2H(sigma2HSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index_C(Index_CSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index_T(Index_TSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_sigma3_S2(Zc1, Zt2, Zc3, Zt3, Yc1, Yt2, Yc3, Yt3, a0H, a1H, a3H, betaH, rho1H, rho2H, sigma1H, sigma2H, Index_C, Index_T));
    return rcpp_result_gen;
END_RCPP
}
// Update_a_S2
Rcpp::List Update_a_S2(arma::mat Zc1, arma::mat Zt2, arma::mat Zc3, arma::mat Zt3, arma::vec Yc1, arma::vec Yt2, arma::vec Yc3, arma::vec Yt3, arma::vec betaH, double rho1H, double rho2H, double sigma1H, double sigma2H, double sigma3H, arma::uvec Index_C, arma::uvec Index_T);
RcppExport SEXP _BatchReMeasure_Update_a_S2(SEXP Zc1SEXP, SEXP Zt2SEXP, SEXP Zc3SEXP, SEXP Zt3SEXP, SEXP Yc1SEXP, SEXP Yt2SEXP, SEXP Yc3SEXP, SEXP Yt3SEXP, SEXP betaHSEXP, SEXP rho1HSEXP, SEXP rho2HSEXP, SEXP sigma1HSEXP, SEXP sigma2HSEXP, SEXP sigma3HSEXP, SEXP Index_CSEXP, SEXP Index_TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Zc1(Zc1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zt2(Zt2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc3(Zc3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zt3(Zt3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc1(Yc1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt2(Yt2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc3(Yc3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt3(Yt3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< double >::type rho1H(rho1HSEXP);
    Rcpp::traits::input_parameter< double >::type rho2H(rho2HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1H(sigma1HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2H(sigma2HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma3H(sigma3HSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index_C(Index_CSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index_T(Index_TSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_a_S2(Zc1, Zt2, Zc3, Zt3, Yc1, Yt2, Yc3, Yt3, betaH, rho1H, rho2H, sigma1H, sigma2H, sigma3H, Index_C, Index_T));
    return rcpp_result_gen;
END_RCPP
}
// Update_beta_S2
arma::vec Update_beta_S2(arma::mat Zc1, arma::mat Zt2, arma::mat Zc3, arma::mat Zt3, arma::vec Yc1, arma::vec Yt2, arma::vec Yc3, arma::vec Yt3, double rho1H, double rho2H, double sigma1H, double sigma2H, double sigma3H, arma::uvec Index_C, arma::uvec Index_T);
RcppExport SEXP _BatchReMeasure_Update_beta_S2(SEXP Zc1SEXP, SEXP Zt2SEXP, SEXP Zc3SEXP, SEXP Zt3SEXP, SEXP Yc1SEXP, SEXP Yt2SEXP, SEXP Yc3SEXP, SEXP Yt3SEXP, SEXP rho1HSEXP, SEXP rho2HSEXP, SEXP sigma1HSEXP, SEXP sigma2HSEXP, SEXP sigma3HSEXP, SEXP Index_CSEXP, SEXP Index_TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Zc1(Zc1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zt2(Zt2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc3(Zc3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zt3(Zt3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc1(Yc1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt2(Yt2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc3(Yc3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt3(Yt3SEXP);
    Rcpp::traits::input_parameter< double >::type rho1H(rho1HSEXP);
    Rcpp::traits::input_parameter< double >::type rho2H(rho2HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1H(sigma1HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2H(sigma2HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma3H(sigma3HSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index_C(Index_CSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index_T(Index_TSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_beta_S2(Zc1, Zt2, Zc3, Zt3, Yc1, Yt2, Yc3, Yt3, rho1H, rho2H, sigma1H, sigma2H, sigma3H, Index_C, Index_T));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_Objective_S2
double Rcpp_Objective_S2(arma::mat Zc1, arma::mat Zt2, arma::mat Zc3, arma::mat Zt3, arma::vec Yc1, arma::vec Yt2, arma::vec Yc3, arma::vec Yt3, arma::vec betaH, double a0H, double a1H, double a3H, double rho1H, double rho2H, double sigma1H, double sigma2H, double sigma3H, arma::uvec Index_C, arma::uvec Index_T);
RcppExport SEXP _BatchReMeasure_Rcpp_Objective_S2(SEXP Zc1SEXP, SEXP Zt2SEXP, SEXP Zc3SEXP, SEXP Zt3SEXP, SEXP Yc1SEXP, SEXP Yt2SEXP, SEXP Yc3SEXP, SEXP Yt3SEXP, SEXP betaHSEXP, SEXP a0HSEXP, SEXP a1HSEXP, SEXP a3HSEXP, SEXP rho1HSEXP, SEXP rho2HSEXP, SEXP sigma1HSEXP, SEXP sigma2HSEXP, SEXP sigma3HSEXP, SEXP Index_CSEXP, SEXP Index_TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Zc1(Zc1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zt2(Zt2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zc3(Zc3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Zt3(Zt3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc1(Yc1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt2(Yt2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yc3(Yc3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt3(Yt3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< double >::type a0H(a0HSEXP);
    Rcpp::traits::input_parameter< double >::type a1H(a1HSEXP);
    Rcpp::traits::input_parameter< double >::type a3H(a3HSEXP);
    Rcpp::traits::input_parameter< double >::type rho1H(rho1HSEXP);
    Rcpp::traits::input_parameter< double >::type rho2H(rho2HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1H(sigma1HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2H(sigma2HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma3H(sigma3HSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index_C(Index_CSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Index_T(Index_TSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_Objective_S2(Zc1, Zt2, Zc3, Zt3, Yc1, Yt2, Yc3, Yt3, betaH, a0H, a1H, a3H, rho1H, rho2H, sigma1H, sigma2H, sigma3H, Index_C, Index_T));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BatchReMeasure_my_setdiff1", (DL_FUNC) &_BatchReMeasure_my_setdiff1, 2},
    {"_BatchReMeasure_Update_rho_S1", (DL_FUNC) &_BatchReMeasure_Update_rho_S1, 10},
    {"_BatchReMeasure_Update_sigma1_S1", (DL_FUNC) &_BatchReMeasure_Update_sigma1_S1, 10},
    {"_BatchReMeasure_Update_sigma2_S1", (DL_FUNC) &_BatchReMeasure_Update_sigma2_S1, 12},
    {"_BatchReMeasure_Update_beta_S1", (DL_FUNC) &_BatchReMeasure_Update_beta_S1, 12},
    {"_BatchReMeasure_Update_a_S1", (DL_FUNC) &_BatchReMeasure_Update_a_S1, 13},
    {"_BatchReMeasure_Rcpp_Objective_S1", (DL_FUNC) &_BatchReMeasure_Rcpp_Objective_S1, 13},
    {"_BatchReMeasure_my_setdiff2", (DL_FUNC) &_BatchReMeasure_my_setdiff2, 2},
    {"_BatchReMeasure_Update_rho1_S2", (DL_FUNC) &_BatchReMeasure_Update_rho1_S2, 9},
    {"_BatchReMeasure_Update_rho2_S2", (DL_FUNC) &_BatchReMeasure_Update_rho2_S2, 11},
    {"_BatchReMeasure_Update_sigma1_S2", (DL_FUNC) &_BatchReMeasure_Update_sigma1_S2, 9},
    {"_BatchReMeasure_Update_sigma2_S2", (DL_FUNC) &_BatchReMeasure_Update_sigma2_S2, 11},
    {"_BatchReMeasure_Update_sigma3_S2", (DL_FUNC) &_BatchReMeasure_Update_sigma3_S2, 18},
    {"_BatchReMeasure_Update_a_S2", (DL_FUNC) &_BatchReMeasure_Update_a_S2, 16},
    {"_BatchReMeasure_Update_beta_S2", (DL_FUNC) &_BatchReMeasure_Update_beta_S2, 15},
    {"_BatchReMeasure_Rcpp_Objective_S2", (DL_FUNC) &_BatchReMeasure_Rcpp_Objective_S2, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_BatchReMeasure(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
