# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

my_setdiff1 <- function(x, y) {
    .Call(`_BatchReMeasure_my_setdiff1`, x, y)
}

Update_rho_S1 <- function(Zc1, Zc2, Yc1, Yc2, a0H, a1H, betaH, sigma1H, sigma2H, Index) {
    .Call(`_BatchReMeasure_Update_rho_S1`, Zc1, Zc2, Yc1, Yc2, a0H, a1H, betaH, sigma1H, sigma2H, Index)
}

Update_sigma1_S1 <- function(Zc1, Zc2, Yc1, Yc2, a0H, a1H, betaH, rhoH, sigma2H, Index) {
    .Call(`_BatchReMeasure_Update_sigma1_S1`, Zc1, Zc2, Yc1, Yc2, a0H, a1H, betaH, rhoH, sigma2H, Index)
}

Update_sigma2_S1 <- function(Zc1, Zt2, Zc2, Yc1, Yt2, Yc2, a0H, a1H, betaH, rhoH, sigma1H, Index) {
    .Call(`_BatchReMeasure_Update_sigma2_S1`, Zc1, Zt2, Zc2, Yc1, Yt2, Yc2, a0H, a1H, betaH, rhoH, sigma1H, Index)
}

Update_beta_S1 <- function(Zc1, Zt2, Zc2, Yc1, Yt2, Yc2, a0H, a1H, rhoH, sigma1H, sigma2H, Index) {
    .Call(`_BatchReMeasure_Update_beta_S1`, Zc1, Zt2, Zc2, Yc1, Yt2, Yc2, a0H, a1H, rhoH, sigma1H, sigma2H, Index)
}

Update_a_S1 <- function(Zc1, Zt2, Zc2, Yc1, Yt2, Yc2, a0H, a1H, betaH, rhoH, sigma1H, sigma2H, Index) {
    .Call(`_BatchReMeasure_Update_a_S1`, Zc1, Zt2, Zc2, Yc1, Yt2, Yc2, a0H, a1H, betaH, rhoH, sigma1H, sigma2H, Index)
}

Rcpp_Objective_S1 <- function(Zc1, Zt2, Zc2, Yc1, Yt2, Yc2, a0H, a1H, betaH, rhoH, sigma1H, sigma2H, Index) {
    .Call(`_BatchReMeasure_Rcpp_Objective_S1`, Zc1, Zt2, Zc2, Yc1, Yt2, Yc2, a0H, a1H, betaH, rhoH, sigma1H, sigma2H, Index)
}

my_setdiff2 <- function(x, y) {
    .Call(`_BatchReMeasure_my_setdiff2`, x, y)
}

Update_rho1_S2 <- function(Zc1, Zc3, Yc1, Yc3, a3H, betaH, sigma1H, sigma3H, Index_C) {
    .Call(`_BatchReMeasure_Update_rho1_S2`, Zc1, Zc3, Yc1, Yc3, a3H, betaH, sigma1H, sigma3H, Index_C)
}

Update_rho2_S2 <- function(Zt2, Zt3, Yt2, Yt3, a0H, a1H, a3H, betaH, sigma2H, sigma3H, Index_T) {
    .Call(`_BatchReMeasure_Update_rho2_S2`, Zt2, Zt3, Yt2, Yt3, a0H, a1H, a3H, betaH, sigma2H, sigma3H, Index_T)
}

Update_sigma1_S2 <- function(Zc1, Zc3, Yc1, Yc3, a3H, betaH, rho1H, sigma3H, Index_C) {
    .Call(`_BatchReMeasure_Update_sigma1_S2`, Zc1, Zc3, Yc1, Yc3, a3H, betaH, rho1H, sigma3H, Index_C)
}

Update_sigma2_S2 <- function(Zt2, Zt3, Yt2, Yt3, a0H, a1H, a3H, betaH, rho2H, sigma3H, Index_T) {
    .Call(`_BatchReMeasure_Update_sigma2_S2`, Zt2, Zt3, Yt2, Yt3, a0H, a1H, a3H, betaH, rho2H, sigma3H, Index_T)
}

Update_sigma3_S2 <- function(Zc1, Zt2, Zc3, Zt3, Yc1, Yt2, Yc3, Yt3, a0H, a1H, a3H, betaH, rho1H, rho2H, sigma1H, sigma2H, Index_C, Index_T) {
    .Call(`_BatchReMeasure_Update_sigma3_S2`, Zc1, Zt2, Zc3, Zt3, Yc1, Yt2, Yc3, Yt3, a0H, a1H, a3H, betaH, rho1H, rho2H, sigma1H, sigma2H, Index_C, Index_T)
}

Update_a_S2 <- function(Zc1, Zt2, Zc3, Zt3, Yc1, Yt2, Yc3, Yt3, betaH, rho1H, rho2H, sigma1H, sigma2H, sigma3H, Index_C, Index_T) {
    .Call(`_BatchReMeasure_Update_a_S2`, Zc1, Zt2, Zc3, Zt3, Yc1, Yt2, Yc3, Yt3, betaH, rho1H, rho2H, sigma1H, sigma2H, sigma3H, Index_C, Index_T)
}

Update_beta_S2 <- function(Zc1, Zt2, Zc3, Zt3, Yc1, Yt2, Yc3, Yt3, rho1H, rho2H, sigma1H, sigma2H, sigma3H, Index_C, Index_T) {
    .Call(`_BatchReMeasure_Update_beta_S2`, Zc1, Zt2, Zc3, Zt3, Yc1, Yt2, Yc3, Yt3, rho1H, rho2H, sigma1H, sigma2H, sigma3H, Index_C, Index_T)
}

Rcpp_Objective_S2 <- function(Zc1, Zt2, Zc3, Zt3, Yc1, Yt2, Yc3, Yt3, betaH, a0H, a1H, a3H, rho1H, rho2H, sigma1H, sigma2H, sigma3H, Index_C, Index_T) {
    .Call(`_BatchReMeasure_Rcpp_Objective_S2`, Zc1, Zt2, Zc3, Zt3, Yc1, Yt2, Yc3, Yt3, betaH, a0H, a1H, a3H, rho1H, rho2H, sigma1H, sigma2H, sigma3H, Index_C, Index_T)
}

